---
title: "L5R Rulings"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  pdf_document: default
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library("httr")
library("jsonlite")
library("lubridate")

options(stringsAsFactors = FALSE)

## This gets the cards for the names

url  <- "http://api.fiveringsdb.com/"
path <- "/cards"
raw.result <- GET(url = url, path = path)
this.raw.content <- rawToChar(raw.result$content)
nchar(this.raw.content)
substr(this.raw.content, 1, 100)
this.content <- fromJSON(this.raw.content)
cards <- this.content[[1]]


## This gets the rulings

url  <- "http://api.fiveringsdb.com/"
path <- "/rulings"
raw.result <- GET(url = url, path = path)
this.raw.content <- rawToChar(raw.result$content)
nchar(this.raw.content)
substr(this.raw.content, 1, 100)
this.content <- fromJSON(this.raw.content)

rulings <- this.content[[1]]
rulings <- rulings[order(rulings$card),]


```

This is a list of all the current rulings from the FiveRingsDB.com website. 


```{r, results='asis', comment=NA, echo=FALSE}

count <- length(rulings$card[,1])

for (i in 1:count){
  cat('\n', "**Card: ", cards[cards$id == rulings$card[i,],]$name, "**\n\n", rulings$text[i],"\n","*Source:",rulings$source[i],"*\n","\n","\n") 
}

```



